### ISSUE TITLE
NameError: global name 'DecryptionException' is not defined

### ISSUE THREAD

**Issue by trancentury** [ryepdx/pyethrecover#3]
hi, 
when executing command `python pyethrecover.py -w ethereum-wallet.json -f passwords.txt` following error appears and system freezed.

`Traceback (most recent call last):
  File "pyethrecover.py", line 171, in __main__
    delayed(attempt)(w, pw, options.verbose) for pw in pwds())
  File "/home/rafix/.local/lib/python2.7/site-packages/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/rafix/.local/lib/python2.7/site-packages/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/rafix/.local/lib/python2.7/site-packages/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/rafix/.local/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/home/rafix/.local/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/home/rafix/.local/lib/python2.7/site-packages/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "pyethrecover.py", line 124, in attempt
    except DecryptionException as e:
NameError: global name 'DecryptionException' is not defined
^CTraceback (most recent call last):
  File "pyethrecover.py", line 182, in <module>
    __main__()
  File "pyethrecover.py", line 177, in __main__
    sys.stdout.flush()
`

Any suggestion ?

**Comment by mdenavac** [comment]
Means it found your password, right ? Did the trick for me. Set `-t 2` to see the command that shows the `attempt`

**Comment by ryepdx** [comment]
@trancentury Does the commit I just pushed resolve the issue for you?
