### ISSUE TITLE
Freeze with 10 letters password

### ISSUE THREAD

**Issue by Sovxx** [ryepdx/pyethrecover#4]
Hi

I am using
Ubuntu 64bit 17.04
python 2.7.13
joblib downloaded from pip
bitcoin downloaded from pip

Using a dummy file just containing:
`{"address":"f5751c906091b98be2a6be5ce42c573d704aedab","crypto":{"cipher":"aes-128-ctr","ciphertext":"de02f574ada7bf81ff77dca34e8dcdbfacd8d569152dcf28bf252a05ee26fe5a","cipherparams":{"iv":"0516b72376a710576d206fd032391325"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"4d709f777732424ab9ef038b5f02b64b19c1cdd811791f0c160696abca69ca7e"},"mac":"08f8a4650e43728bc5d79d43e02d018b99d0ff61cf7ed9eb2f1de080ceb6f19d"},"id":"1f7cfd33-f43c-4c2a-ad52-e99f6058dab3","version":3}`

If I run a test with a password up to 9 letter long, nothing happens ; I just get a new prompt
`benoit@benoit-MS-7971:~/pyethrecover-master$ python pyethrecover.py -w dummy -p testtestt
benoit@benoit-MS-7971:~/pyethrecover-master$`

But if I use a 10 letter long password, it freezes and I get then following message (had to press CRTL+C to stop freezing):
`benoit@benoit-MS-7971:~/pyethrecover-master$ python pyethrecover.py -w dummy -p testtestte
testtestte
Traceback (most recent call last):
  File "pyethrecover.py", line 221, in __main__
    Parallel(n_jobs=-1)(delayed(attempt)(w, pw) for pw in pwds)
  File "/home/benoit/.local/lib/python2.7/site-packages/joblib/parallel.py", line 789, in __call__
    self.retrieve()
  File "/home/benoit/.local/lib/python2.7/site-packages/joblib/parallel.py", line 740, in retrieve
    raise exception
JoblibKeyError: JoblibKeyError
___________________________________________________________________________
Multiprocessing exception:
...........................................................................
/home/benoit/pyethrecover-master/pyethrecover.py in <module>()
    224         while True:
    225             sys.stdout.write('\a')
    226             sys.stdout.flush()
    227 
    228 if __name__ == "__main__":
--> 229     __main__()

...........................................................................
/home/benoit/pyethrecover-master/pyethrecover.py in __main__()
    216         grammar = eval(open(options.pwsfile, 'r').read())
    217         pwds = itertools.chain(pwds, generate_all(grammar,''))
    218 
    219 
    220     try:
--> 221         Parallel(n_jobs=-1)(delayed(attempt)(w, pw) for pw in pwds)
        pwds = ['testtestte']
    222     except Exception, e:
    223         traceback.print_exc()
    224         while True:
    225             sys.stdout.write('\a')

...........................................................................
/home/benoit/.local/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=Parallel(n_jobs=-1), iterable=<generator object <genexpr>>)
    784             if pre_dispatch == "all" or n_jobs == 1:
    785                 # The iterable was consumed all at once by the above for loop.
    786                 # No need to wait for async callbacks to trigger to
    787                 # consumption.
    788                 self._iterating = False
--> 789             self.retrieve()
        self.retrieve = <bound method Parallel.retrieve of Parallel(n_jobs=-1)>
    790             # Make sure that we get a last message telling us we are done
    791             elapsed_time = time.time() - self._start_time
    792             self._print('Done %3i out of %3i | elapsed: %s finished',
    793                         (len(self._output), len(self._output),

---------------------------------------------------------------------------
Sub-process traceback:
---------------------------------------------------------------------------
KeyError                                           Wed Sep 27 22:58:08 2017
PID: 2763                                    Python 2.7.13: /usr/bin/python
...........................................................................
/home/benoit/.local/lib/python2.7/site-packages/joblib/parallel.py in __call__(self=<joblib.parallel.BatchedCalls object>)
    126     def __init__(self, iterator_slice):
    127         self.items = list(iterator_slice)
    128         self._size = len(self.items)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
        func = <function attempt>
        args = ({u'address': u'f5751c906091b98be2a6be5ce42c573d704aedab', u'crypto': {u'cipher': u'aes-128-ctr', u'cipherparams': {u'iv': u'0516b72376a710576d206fd032391325'}, u'ciphertext': u'de02f574ada7bf81ff77dca34e8dcdbfacd8d569152dcf28bf252a05ee26fe5a', u'kdf': u'scrypt', u'kdfparams': {u'dklen': 32, u'n': 262144, u'p': 1, u'r': 8, u'salt': u'4d709f777732424ab9ef038b5f02b64b19c1cdd811791f0c160696abca69ca7e'}, u'mac': u'08f8a4650e43728bc5d79d43e02d018b99d0ff61cf7ed9eb2f1de080ceb6f19d'}, u'id': u'1f7cfd33-f43c-4c2a-ad52-e99f6058dab3', u'version': 3}, 'testtestte')
        kwargs = {}
        self.items = [(<function attempt>, ({u'address': u'f5751c906091b98be2a6be5ce42c573d704aedab', u'crypto': {u'cipher': u'aes-128-ctr', u'cipherparams': {u'iv': u'0516b72376a710576d206fd032391325'}, u'ciphertext': u'de02f574ada7bf81ff77dca34e8dcdbfacd8d569152dcf28bf252a05ee26fe5a', u'kdf': u'scrypt', u'kdfparams': {u'dklen': 32, u'n': 262144, u'p': 1, u'r': 8, u'salt': u'4d709f777732424ab9ef038b5f02b64b19c1cdd811791f0c160696abca69ca7e'}, u'mac': u'08f8a4650e43728bc5d79d43e02d018b99d0ff61cf7ed9eb2f1de080ceb6f19d'}, u'id': u'1f7cfd33-f43c-4c2a-ad52-e99f6058dab3', u'version': 3}, 'testtestte'), {})]
    132 
    133     def __len__(self):
    134         return self._size
    135 

...........................................................................
/home/benoit/pyethrecover-master/pyethrecover.py in attempt(w={u'address': u'f5751c906091b98be2a6be5ce42c573d704aedab', u'crypto': {u'cipher': u'aes-128-ctr', u'cipherparams': {u'iv': u'0516b72376a710576d206fd032391325'}, u'ciphertext': u'de02f574ada7bf81ff77dca34e8dcdbfacd8d569152dcf28bf252a05ee26fe5a', u'kdf': u'scrypt', u'kdfparams': {u'dklen': 32, u'n': 262144, u'p': 1, u'r': 8, u'salt': u'4d709f777732424ab9ef038b5f02b64b19c1cdd811791f0c160696abca69ca7e'}, u'mac': u'08f8a4650e43728bc5d79d43e02d018b99d0ff61cf7ed9eb2f1de080ceb6f19d'}, u'id': u'1f7cfd33-f43c-4c2a-ad52-e99f6058dab3', u'version': 3}, pw='testtestte')
    183     if len(pw) < 10:
    184         return ""
    185     try:
    186         print (pw)
    187         raise PasswordFoundException(
--> 188             """\n\nYour seed is:\n%s\nYour password is:\n%s""" % (getseed(w['encseed'], pbkdf2(pw), w['ethaddr']), pw))
        w = {u'address': u'f5751c906091b98be2a6be5ce42c573d704aedab', u'crypto': {u'cipher': u'aes-128-ctr', u'cipherparams': {u'iv': u'0516b72376a710576d206fd032391325'}, u'ciphertext': u'de02f574ada7bf81ff77dca34e8dcdbfacd8d569152dcf28bf252a05ee26fe5a', u'kdf': u'scrypt', u'kdfparams': {u'dklen': 32, u'n': 262144, u'p': 1, u'r': 8, u'salt': u'4d709f777732424ab9ef038b5f02b64b19c1cdd811791f0c160696abca69ca7e'}, u'mac': u'08f8a4650e43728bc5d79d43e02d018b99d0ff61cf7ed9eb2f1de080ceb6f19d'}, u'id': u'1f7cfd33-f43c-4c2a-ad52-e99f6058dab3', u'version': 3}
        pw = 'testtestte'
    189 
    190     except DecryptionException as e:
    191         # print(e)
    192         return ""

KeyError: 'encseed'
___________________________________________________________________________
`

**Comment by Sovxx** [comment]
Using python3, things look different:
`benoit@benoit-MS-7971:~/pyethrecover-master$ python3 pyethrecover.py -w dummy -p testtestt
  File "pyethrecover.py", line 134
    except Exception, e:
                    ^
SyntaxError: invalid syntax
`
`
benoit@benoit-MS-7971:~/pyethrecover-master$ python3 pyethrecover.py -w dummy -p testtestte
  File "pyethrecover.py", line 134
    except Exception, e:
                    ^
SyntaxError: invalid syntax
`
`
benoit@benoit-MS-7971:~/pyethrecover-master$ 
`

**Comment by Sovxx** [comment]
Sigh
I was just using an older version...
Sorry !
close #4
